
# /Users/haoxun/Data/Project/sdataflow/sdataflow/ast/generated_parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xfa\xcaWq\x19Oe\x1e%6K\x89\xd1R\xfa\x94'
    
_lr_action_items = {u'DOUBLE_HYPHENS':([8,],[12,]),u'ARROW':([7,8,15,17,],[11,13,-9,20,]),u'BRACKET_LEFT':([0,1,2,4,5,6,9,12,13,15,16,18,19,],[3,3,-3,-5,-2,-4,-1,3,3,-9,-11,-10,-6,]),u'BRACKET_RIGHT':([10,],[15,]),u'ID':([0,1,2,3,4,5,6,9,11,13,14,15,16,18,19,20,],[8,8,-3,10,-5,-2,-4,-1,16,-7,19,-9,-11,-10,-6,-8,]),'$end':([1,2,4,5,6,9,15,16,18,19,],[0,-3,-5,-2,-4,-1,-9,-11,-10,-6,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {u'stats':([0,],[1,]),u'entry_to_entry':([0,1,],[2,2,]),u'outcome_type':([0,1,12,13,],[7,7,17,18,]),u'outcome_type_to_entry':([0,1,],[4,4,]),u'single_stat':([0,1,],[5,9,]),u'entry_to_outcome_type':([0,1,],[6,6,]),u'general_arrow':([8,],[14,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> stats","S'",1,None,None,None),
  (u'stats -> stats single_stat',u'stats',2,'p_stats','/Users/haoxun/Data/Project/sdataflow/sdataflow/ast/parser.py',33),
  (u'stats -> single_stat',u'stats',1,'p_stats','/Users/haoxun/Data/Project/sdataflow/sdataflow/ast/parser.py',34),
  (u'single_stat -> entry_to_entry',u'single_stat',1,'p_single_stat','/Users/haoxun/Data/Project/sdataflow/sdataflow/ast/parser.py',44),
  (u'single_stat -> entry_to_outcome_type',u'single_stat',1,'p_single_stat','/Users/haoxun/Data/Project/sdataflow/sdataflow/ast/parser.py',45),
  (u'single_stat -> outcome_type_to_entry',u'single_stat',1,'p_single_stat','/Users/haoxun/Data/Project/sdataflow/sdataflow/ast/parser.py',46),
  (u'entry_to_entry -> ID general_arrow ID',u'entry_to_entry',3,'p_entry_to_entry','/Users/haoxun/Data/Project/sdataflow/sdataflow/ast/parser.py',51),
  (u'general_arrow -> ARROW',u'general_arrow',1,'p_general_arrow','/Users/haoxun/Data/Project/sdataflow/sdataflow/ast/parser.py',64),
  (u'general_arrow -> DOUBLE_HYPHENS outcome_type ARROW',u'general_arrow',3,'p_general_arrow','/Users/haoxun/Data/Project/sdataflow/sdataflow/ast/parser.py',65),
  (u'outcome_type -> BRACKET_LEFT ID BRACKET_RIGHT',u'outcome_type',3,'p_outcome_type','/Users/haoxun/Data/Project/sdataflow/sdataflow/ast/parser.py',73),
  (u'entry_to_outcome_type -> ID ARROW outcome_type',u'entry_to_outcome_type',3,'p_entry_to_outcome_type','/Users/haoxun/Data/Project/sdataflow/sdataflow/ast/parser.py',78),
  (u'outcome_type_to_entry -> outcome_type ARROW ID',u'outcome_type_to_entry',3,'p_outcome_type_to_entry','/Users/haoxun/Data/Project/sdataflow/sdataflow/ast/parser.py',83),
]
